version: 2.1

orbs:
  terraform: circleci/terraform@1.1.0

jobs:
  plan-infra:
    executor: terraform/default
    steps:
      - checkout
      - run:
          name: "Check commits of the PR branch"
          command: ./.circleci/check_commits.sh
      - terraform/fmt: {}
      - terraform/plan: {}

workflows:
  plan-infra:
    jobs:
      - plan-infra:
          filters:
            branches:
              ignore:
                - master

  deploy-infra:
    jobs:
      - terraform/apply:
          name: deploy-infra
          checkout: true
          filters:
            branches:
              only:
                - master
