name: "Deploy"
on:
  push:
    branches:
      - master
jobs:
  build:
    name: "Deploy infra"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_prod_postgres_password: ${{ secrets.TF_VAR_prod_postgres_password }}
      TF_VAR_prod_postgres_username: ${{ secrets.TF_VAR_prod_postgres_username }}
      TF_VAR_staging_postgres_password: ${{ secrets.TF_VAR_staging_postgres_password }}
      TF_VAR_staging_postgres_username: ${{ secrets.TF_VAR_staging_postgres_username }}
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1

      - name: "Terraform init"
        id: init
        run: terraform init

      - name: "Terraform apply"
        run: terraform apply
